# Generated by Django 3.2.17 on 2023-06-23 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userloginactivity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedbackstudent',
            old_name='user',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='notificationstudent',
            old_name='user',
            new_name='student_id',
        ),
        migrations.AddField(
            model_name='notificationstudent',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificationstudent',
            name='read',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='StudentResult',
        ),
    ]
