# Generated by Django 3.2.17 on 2023-06-23 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20230623_1233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profile_student',
            name='profile_pic',
        ),
    ]
