# Generated by Django 3.2.17 on 2023-03-29 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0004_codinglesson_codingsubject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codinglesson',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aicoding_lessons', to='curriculum.codingsubject'),
        ),
    ]
