# Generated by Django 3.2.20 on 2023-08-10 17:34

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0007_mechanzo_kit_name_mechanzo_model_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mechanzo_kit_name',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, default=None, editable=False, null=True, populate_from=models.CharField(max_length=50)),
        ),
        migrations.AlterField(
            model_name='mechanzo_model_name',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, default=None, editable=False, null=True, populate_from=models.CharField(max_length=50)),
        ),
    ]
