# Generated by Django 3.2.20 on 2023-08-10 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0008_auto_20230810_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mechanzo_kit_name',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mechanzo_model_name',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
